// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndUpdate() {
  return window['go']['selfupdater']['Updater']['CheckAndUpdate']();
}

export function CheckLatest() {
  return window['go']['selfupdater']['Updater']['CheckLatest']();
}

export function Update() {
  return window['go']['selfupdater']['Updater']['Update']();
}
