// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndUpdate():Promise<void>;

export function CheckLatest():Promise<boolean>;

export function Update():Promise<void>;
