// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScore(arg1) {
  return window['go']['score']['ScoreService']['AddScore'](arg1);
}

export function GetScore(arg1) {
  return window['go']['score']['ScoreService']['GetScore'](arg1);
}
