// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {score} from '../models';

export function AddScore(arg1:score.Score):Promise<void>;

export function GetScore(arg1:score.GameEnum,arg2:score.DifficultyLevel):Promise<Array<score.Score>>;
