name: Wails build

on:
  workflow_dispatch:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'mult-game'
            platform:  'linux/amd64'
            arch: 'linux-amd64'
            os: 'ubuntu-latest'
          - name: 'mult-game'
            platform:  'windows/amd64'
            arch: 'windows-amd64'
            os: 'windows-latest'
          - name: 'mult-game'
            platform:  'darwin/universal'
            os: 'macos-latest'
            arch: 'darwin-universal'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}_${{ matrix.build.arch }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.21'
      # - name: Build Windows App + Installer
      #   run: wails build --platform windows/amd64 -webview2 download -nsis -o 'mult-game-installer'
      #   shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} mult-game
          path: |
            */bin/
            *\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*
